name: Launcher
run-name: Auto Update Version

on:
  schedule:
    - cron: 0 16 * * *
  push:
    branches:
      - main
  workflow_dispatch:

# 添加权限配置
permissions:
  contents: write

jobs:
  update:
    name: Update Launcher
    runs-on: ubuntu-latest
    continue-on-error: true
    outputs:
      fcl_version: ${{ steps.get.outputs.fcl_version }}
    strategy:
      fail-fast: false
      max-parallel: 1
      matrix:
        include:
          - abbr: FCL
            github: https://github.com/FCL-Team/FoldCraftLauncher
    steps:
      - uses: actions/checkout@main
      - name: Handle files
        id: handle
        run: |
          git pull --rebase
          API=`echo ${{ matrix.github }} | sed 's/:\/\/github\.com\//:\/\/api.github.com\/repos\//g' | sed 's/$/\/releases/g'`
          wget -O latest.json $API/latest || echo '{"tag_name":""}' > latest.json
          wget -O releases.json $API
          
          # 检查 data 目录是否存在，不存在则创建
          if [ ! -d "data" ]; then
            mkdir -p data
          fi
          
          # 检查 launcher.json5 文件是否存在，不存在则创建一个基本的空白文件
          if [ ! -f "data/launcher.json5" ]; then
            echo '{
              "FCL": {
                "version": "0.0.0",
                "dev": {
                  "version": "0.0.0"
                }
              }
            }' > data/launcher.json5
            echo "创建了新的 launcher.json5 文件，因为原文件不存在"
          fi
          
          if [ '${{ matrix.device }}' ]; then
            DEVICE_LIST=`echo '${{ matrix.device }}' | sed 's/|/\\\\|/g'`
            sed -n '/\('"$DEVICE_LIST"'\)Launcher/,/]/p' data/launcher.json5 > launcher.json5
          else
            cp data/launcher.json5 launcher.json5
          fi
      - name: Get ${{ matrix.abbr }} version
        id: get
        run: |
          # 下载FCL官方的version_map.json获取最新版本
          echo "正在从FCL官方仓库获取版本信息..."
          wget -O version_map.json https://raw.githubusercontent.com/FCL-Team/FoldCraftLauncher/main/version_map.json
          
          # 提取最新版本信息 (第一个条目)
          LATEST_VERSION_NAME=$(cat version_map.json | jq -r '.[0].versionName')
          LATEST_VERSION_DATE=$(cat version_map.json | jq -r '.[0].date')
          LATEST_VERSION_URL=$(cat version_map.json | jq -r '.[0].url')
          LATEST_VERSION_TYPE=$(cat version_map.json | jq -r '.[0].type')
          
          echo "获取到的版本信息:"
          echo "版本名称: $LATEST_VERSION_NAME"
          echo "发布日期: $LATEST_VERSION_DATE"
          echo "下载地址: $LATEST_VERSION_URL"
          echo "版本类型: $LATEST_VERSION_TYPE"
          
          # 直接从URL中提取文件前缀 - 更可靠的方法
          FILE_PREFIX=$(echo $LATEST_VERSION_URL | sed -E 's|.*/([^/]+)-[0-9.]+.*\.apk$|\1|')
          
          # 确保FILE_PREFIX非空，否则使用默认值
          if [ -z "$FILE_PREFIX" ]; then
            echo "从URL中无法提取文件前缀，使用默认值"
            FILE_PREFIX="FCL-release"
          fi
          
          echo "文件前缀: $FILE_PREFIX"
          
          # 提取版本号用于更新launcher.json5
          # Get Last Stable ${{ matrix.abbr }}
          LAST_STABLE_VERSION=`sed -n '/"${{ matrix.abbr }}"/,/"version":/p' launcher.json5 | sed -n '$p' | sed 's/^.*:\s*"v\?\|",$//gi' | sed 's/\./\\\\./g'`
          
          # Get Last Dev ${{ matrix.abbr }}
          LAST_DEV_VERSION=`sed -n '/"${{ matrix.abbr }}"/,/}/p' launcher.json5 | sed -n '/"dev":/,/"version":/p' | sed -n '$p' | sed 's/^.*:\s*"v\?\|"$//gi' | sed 's/\./\\\\./g'`
          
          # 使用version_map.json中的版本作为最新稳定版
          LATEST_STABLE_VERSION=`echo $LATEST_VERSION_NAME | sed 's/\./\\\\./g'`
          
          # 确保版本号非空
          if [ -z "$LATEST_VERSION_NAME" ]; then
            echo "警告: 无法从version_map.json获取版本号，使用硬编码的默认版本"
            LATEST_VERSION_NAME="1.2.1.1"
            LATEST_STABLE_VERSION="1\\.2\\.1\\.1"
          fi
          
          # 保存下载URL格式供后续任务使用
          echo "FCL_VERSION=$LATEST_VERSION_NAME" >> $GITHUB_ENV
          echo "FCL_DATE=$LATEST_VERSION_DATE" >> $GITHUB_ENV
          echo "FCL_FILE_PREFIX=$FILE_PREFIX" >> $GITHUB_ENV
          
          # 输出变量
          echo "fcl_version=$LATEST_VERSION_NAME" >> $GITHUB_OUTPUT
          echo "fcl_date=$LATEST_VERSION_DATE" >> $GITHUB_OUTPUT
          echo "fcl_file_prefix=$FILE_PREFIX" >> $GITHUB_OUTPUT
          
          # Remove Needless Files
          rm version_map.json launcher.json5
          
          # Output
          echo "last_stable_version=$LAST_STABLE_VERSION" >> $GITHUB_OUTPUT
          echo "last_dev_version=$LAST_DEV_VERSION" >> $GITHUB_OUTPUT
          echo "latest_stable_version=$LATEST_STABLE_VERSION" >> $GITHUB_OUTPUT
          echo "latest_dev_version=$LATEST_DEV_VERSION" >> $GITHUB_OUTPUT
      - name: Modify launcher.json5
        id: modify
        run: |
          LAST_STABLE_VERSION='${{ steps.get.outputs.last_stable_version }}'
          LAST_DEV_VERSION='${{ steps.get.outputs.last_dev_version }}'
          LATEST_STABLE_VERSION='${{ steps.get.outputs.latest_stable_version }}'
          LATEST_DEV_VERSION='${{ steps.get.outputs.latest_dev_version }}'
          if [ '${{ matrix.device }}' ]; then
            DEVICE_STRING=' [${{ matrix.device }}]'
          else
            DEVICE_STRING=''
          fi
          if [ "$LATEST_STABLE_VERSION" ]; then
            if [ "$LAST_STABLE_VERSION" != "$LATEST_STABLE_VERSION" ]; then
              sed -i 's/\([/"v-]\)'"$LAST_STABLE_VERSION"'\(\.[a-z]\|["/-]\)/\1'"$LATEST_STABLE_VERSION"'\2/gi' data/launcher.json5
              LAST_STABLE_VERSION=`echo $LAST_STABLE_VERSION | sed 's/\\\\././g'`
              LATEST_STABLE_VERSION=`echo $LATEST_STABLE_VERSION | sed 's/\\\\././g'`
              CHANGELOG_E='  ${{ matrix.abbr }}(stable): '"$LAST_STABLE_VERSION => $LATEST_STABLE_VERSION$DEVICE_STRING"
            fi
          fi
          if [ "$LATEST_DEV_VERSION" ]; then
            if [ "$LAST_DEV_VERSION" != "$LATEST_DEV_VERSION" ]; then
              sed -i 's/\([/"v-]\)'"$LAST_DEV_VERSION"'\(\.[a-z]\|["/-]\)/\1'"$LATEST_DEV_VERSION"'\2/gi' data/launcher.json5
              LAST_DEV_VERSION=`echo $LAST_DEV_VERSION | sed 's/\\\\././g'`
              LATEST_DEV_VERSION=`echo $LATEST_DEV_VERSION | sed 's/\\\\././g'`
              if [ "$CHANGELOG_E" ]; then
                CHANGELOG_E="${CHANGELOG_E}"'#n  ${{ matrix.abbr }}(dev): '"$LAST_DEV_VERSION => $LATEST_DEV_VERSION$DEVICE_STRING"
              else
                CHANGELOG_E='  ${{ matrix.abbr }}(dev): '"$LAST_DEV_VERSION => $LATEST_DEV_VERSION$DEVICE_STRING"
              fi
            fi
          fi
          if [ "$CHANGELOG_E" ]; then
            CHANGELOG=`echo "$CHANGELOG_E" | sed 's/#n/\n/g'`
            echo ===============================================================
            echo "$CHANGELOG"
            echo ===============================================================
          fi
          MESSAGE='modify: update ${{ matrix.abbr }}
          
          [Auto] Update Launcher Version:
          '"$CHANGELOG
          (Time: `date +'%F %X %Z'`)"
          EOF=$(dd if=/dev/urandom bs=15 count=1 status=none | base64)  # To define the separator
          echo "message<<EOF"$'\n'"$MESSAGE"$'\n'EOF >> $GITHUB_OUTPUT  # For the multi-line output
      - name: Commit & Push
        id: commit_and_push
        uses: EndBug/add-and-commit@main
        with:
          default_author: github_actions
          message: ${{ steps.modify.outputs.message }}

      # 输出将被传递给下一个任务的版本号
      - name: Echo version for next job
        run: |
          echo "FCL版本号: ${{ env.FCL_VERSION }}"
          echo "FCL发布日期: ${{ env.FCL_DATE }}"
          echo "FCL文件前缀: ${{ env.FCL_FILE_PREFIX }}"

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: update
    env:
      FCL_VERSION: ${{ needs.update.outputs.fcl_version }}
      FCL_DATE: ${{ needs.update.outputs.fcl_date }}
      FCL_FILE_PREFIX: ${{ needs.update.outputs.fcl_file_prefix }}
    steps:
      - name: Echo version information
        run: |
          echo "fcl_version: ${{ env.FCL_VERSION }}"
      
      - uses: actions/checkout@main

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22.x

      - name: Install Docusaurus
        run: | 
          npm install

      - name: Build Docusaurus
        run: |
          npm run build
          
      - name: Deploy to Server
        uses: fifsky/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          port: ${{ secrets.PORT }}
          user: ${{ secrets.HOST_USERNAME }}
          key: ${{ secrets.KEY }}
          pass: ${{ secrets.HOST_PASSWORD }}
          args: -o StrictHostKeyChecking=no
          command: |
            # 在服务器上创建必要的目录
            mkdir -p /tmp/fcl-deploy /tmp/fcl-updates
            
            # 清理旧的临时文件
            rm -rf /tmp/fcl-deploy/* /tmp/fcl-updates/*
      
      - name: Copy Docusaurus to Server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.HOST_USERNAME }}
          port: ${{ secrets.PORT }}
          key: ${{ secrets.KEY }}
          password: ${{ secrets.HOST_PASSWORD }}
          source: "build/"
          target: "/tmp/fcl-deploy"
          
      - name: Run remote commands
        id: run
        uses: fifsky/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          port: ${{ secrets.PORT }}
          user: ${{ secrets.HOST_USERNAME }}
          key: ${{ secrets.KEY }}
          pass: ${{ secrets.HOST_PASSWORD }}
          args: -o StrictHostKeyChecking=no
          command: |
            # 部署Docusaurus构建文件
            cd /tmp/fcl-deploy
            if [ -d "./build" ]; then
              mkdir -p /1p/1panel/apps/openresty/openresty/www/sites/fcl.ningmo.fun/index/
              cp -R ./build/* /1p/1panel/apps/openresty/openresty/www/sites/fcl.ningmo.fun/index/
              echo "Deployed build files successfully"
            fi
            
            # 转到FCL下载目录
            cd /tmp/fcl-updates
            
            # 获取FCL版本信息
            FCL_VERSION="${{ env.FCL_VERSION }}"
            FCL_DATE="${{ env.FCL_DATE }}"
            FCL_FILE_PREFIX="${{ env.FCL_FILE_PREFIX }}"
            
            echo "FCL版本: $FCL_VERSION"
            echo "FCL发布日期: $FCL_DATE"
            echo "FCL文件前缀: $FCL_FILE_PREFIX"
            
            # 确保版本信息非空
            if [ -z "$FCL_VERSION" ]; then
              echo "警告: 版本号为空，使用硬编码的默认版本"
              FCL_VERSION="1.2.1.1"
            fi
            
            # 确保文件前缀非空
            if [ -z "$FCL_FILE_PREFIX" ]; then
              echo "警告: 文件前缀为空，使用硬编码的默认前缀"
              FCL_FILE_PREFIX="FCL-release"
            fi
            
            # 构建基础下载URL
            BASE_URL="https://github.com/FCL-Team/FoldCraftLauncher/releases/download"
            
            # 下载函数，包含重试逻辑
            download_file() {
              local url=$1
              local output=$2
              local max_retries=3
              local retry=0
              
              echo "完整下载URL: $url"
              echo "输出文件: $output"
              
              while [ $retry -lt $max_retries ]; do
                echo "尝试下载 $url (尝试 $((retry+1))/$max_retries)"
                wget -q "$url" -O "$output" 
                
                if [ -f "$output" ] && [ -s "$output" ]; then
                  echo "✅ $output 下载成功"
                  return 0
                else
                  echo "❌ $output 下载失败或为空"
                  retry=$((retry+1))
                  if [ $retry -lt $max_retries ]; then
                    echo "等待5秒后重试..."
                    sleep 5
                  fi
                fi
              done
              
              return 1
            }
            
            # 下载FCL启动器的三个版本，使用正确的文件名格式
            echo "正在下载x86版本..."
            X86_URL="$BASE_URL/$FCL_VERSION/${FCL_FILE_PREFIX}-${FCL_VERSION}-x86.apk"
            download_file "$X86_URL" "FCL-v${FCL_VERSION}-x86.apk"
            
            echo "正在下载arm64-v8a版本..."
            ARM64_URL="$BASE_URL/$FCL_VERSION/${FCL_FILE_PREFIX}-${FCL_VERSION}-arm64-v8a.apk"
            download_file "$ARM64_URL" "FCL-v${FCL_VERSION}-arm64-v8a.apk"
            
            echo "正在下载all版本..."
            ALL_URL="$BASE_URL/$FCL_VERSION/${FCL_FILE_PREFIX}-${FCL_VERSION}-all.apk"
            download_file "$ALL_URL" "FCL-v${FCL_VERSION}-all.apk"
            
            # 创建版本索引文件
            echo "{\"version\":\"$FCL_VERSION\",\"releaseTime\":\"$FCL_DATE\"}" > version.json
            
            # 列出下载的文件
            echo "已下载的文件:"
            ls -la
            
            # 检查至少有一个文件下载成功（更新文件名检查）
            if [ ! -f "FCL-v${FCL_VERSION}-x86.apk" ] && [ ! -f "FCL-v${FCL_VERSION}-arm64-v8a.apk" ] && [ ! -f "FCL-v${FCL_VERSION}-all.apk" ]; then
              echo "错误：所有版本下载均失败，无法继续部署"
              exit 1
            fi
            
            # 一次性部署FCL启动器文件到两个目标位置
            for TARGET in "/1p/1panel/apps/openresty/openresty/www/sites/cf.ningmo.fun/index/fcl" "/1p/1panel/apps/openresty/openresty/www/sites/fcl.ningmo.fun/index/fcl"; do
              mkdir -p $TARGET
              cp -R * $TARGET/
              echo "部署到 $TARGET 完成"
            done
            
            # 清理临时文件
            cd /tmp
            rm -rf fcl-deploy fcl-updates
